---
# - name: DNF copr enable pennbauman
#   command:
#     cmd: "dnf copr enable pennbauman/ports"
#     creates: /etc/yum.repos.d/_copr_ganto-lxd.repo
#
# - name: Enable Fedora Copr for LXD
#   community.general.copr:
#     name: ganto/lxd
#
#

- name: Add Mullvad Repo
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo https://repository.mullvad.net/rpm/stable/mullvad.repo
  args:
    creates: /etc/yum.repos.d/mullvad-vpn.repo

- name: Enable Fedora Copr for pennbauman
  community.general.copr:
    name: pennbauman/ports

- name: Install GUI packages
  ansible.builtin.dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - alacritty
      - aspell
      - aspell-en
      - autoconf
      - autogen
      - automake
      - boost
      - btop
      - cargo
      - chromium
      - entr # Needed by tmux plugins
      - fprintd
      - gcc
      - git-delta
      - go
      - inkscape
      - isync
      - kio-admin
      - kitty
      - lf
      - lynx
      - make
      - mpc
      - mpv
      - mksh
      - most
      - neomutt
      - newsboat
      - npm
      - openssh-server
      - openssl-devel
      - pandoc
      - patch # for compiling tmux
      - ranger
      - rust
      - syncthing
      - task
      - task # taskwiki will fail without these
      - timew
      - w3m
      - weechat
      - wl-clipboard
      - yq
      - ImageMagick-devel
      - mullvad-vpn
      # - asdf
      # - chezmoi
      # - fprint
      # - glow
      # - go-yq
      # - gopass
      # - gopass-hibp
      # - gopass-jsonapi
      # - gopass-summon-provider
      # - mpd
      # - python-pip
      # - python-pipx
      # - python-pynvim
      # - python-pyserial
      # - python-virtualenv
      # - tmatrix
      # - ueberzugpp
      # - wmctl
      # - wmutils
      # - stl-thumb-kde
# - name: Start and enable Pueue Service
#   systemd:
#     name: pueued
#     state: started
#     enabled: yes
#     scope: user

# - name: Check if nvm is installed
#   shell: nvm --version
#   register: nvm_version_cmd
#   changed_when: false
#   ignore_errors: true
#
# - name: Install nvm
#   shell: wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
#   when: nvm_version_cmd is failed
