---
- name: Install pre-requisites to run the main playbook
  hosts: all

  tasks:
    - name: Install ansible-galaxy requirements.
      ansible.builtin.command: ansible-galaxy install -r requirements.yaml
  # command: ansible-galaxy install {{ item.item }}
  # with_items:
  #   - "{{ ansible_roles_list }}"
