---
- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install multiple packages
  community.general.flatpak:
    name:
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.mozilla.firefox
      - org.inkscape.Inkscape
      - org.kde.krita
      - org.kde.arianna
      - md.obsidian.Obsidian
      - org.videolan.VLC
