---
- name: Add the flathub flatpak repository remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

- name: Install multiple flatpak packages
  community.general.flatpak:
    name:
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.mozilla.firefox
      - org.inkscape.Inkscape
      - org.kde.krita
      - org.kde.arianna
      - md.obsidian.Obsidian
      - org.videolan.VLC
      - com.calibre_ebook.calibre
      - org.upscayl.Upscayl
      - com.github.jeromerobert.pdfarranger
# flatpak permission-set webextensions tridactyl snap.firefox yes
# flatpak override --user --filesystem=~/.mozilla org.mozilla.firefox
# flatpak run --env=MOZ_ENABLE_WAYLAND=1 org.mozilla.firefox
