---
- name: Install multiple flatpak packages
  community.general.flatpak:
    name:
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.mozilla.firefox
      - org.kde.krita
      - org.kde.arianna
      - md.obsidian.Obsidian
      - org.videolan.VLC
      - com.calibre_ebook.calibre
      - com.github.jeromerobert.pdfarranger
      - com.github.wwmm.easyeffects
      - org.prismlauncher.PrismLauncher
      - org.upscayl.Upscayl
      - com.valvesoftware.Steam
      - io.github.martchus.syncthingtray
      # - com.librumreader.librum

- name: Install OpenSCAD from flathub-beta
  community.general.flatpak:
    name: org.openscad.OpenSCAD
    remote: flathub-beta
# flatpak override com.calibre_ebook.calibre --user --filesystem=~/.config/calibre
# flatpak override org.mozilla.firefox --user --filesystem=~/.mozilla
# Allow access to /tmp for firefox
# sudo flatpak override org.mozilla.firefox --filesystem=/tmp
# flatpak install flathub io.github.btpf.alexandria
# flatpak install flathub org.kde.arianna
# flatpak install flathub com.github.babluboy.bookworm
# flatpak install flathub com.ultimaker.cura
# flatpak permission-set webextensions tridactyl snap.firefox yes
# flatpak run --env=MOZ_ENABLE_WAYLAND=1 org.mozilla.firefox
