---
- name: "Add my Github keys to root authorized_keys"
  ansible.posix.authorized_key:
    user: root
    state: present
    key: https://github.com/fullstopslash.keys

- name: install Ansible Galaxy requirements via the pull playbook itself
  ansible.builtin.command: ansible-galaxy install -r requirements.yml
